///<reference path="./modeling.d.js" />
import Model from './model.js';

/**
 * The base class for `ProductModel` instances for the "products" storage resource.
 * Exported: 2022-05-26T03:58:45.543Z
 *
 * **WARNING**    
 * THIS CLASS IS AUTOMATICALLY GENERATED DURING STASHKU OPTIONS EXPORTS.    
 * CUSTOMIZATIONS WILL BE OVERWRITTEN ON NEW OPTIONS EXPORTS.    
 * Use the non-autogenerated (base) class files to add unique customizations.
 */
class BaseProductModel extends Model {
    constructor() {
        super();
        
        /**
         * @type {Number}
         */
        this.Cost = this.constructor.Cost.default ?? null;
        
        /**
         * @type {String}
         */
        this.DateCreated = this.constructor.DateCreated.default ?? null;
        
        /**
         * @type {String}
         */
        this.DateDeleted = this.constructor.DateDeleted.default ?? null;
        
        /**
         * @type {String}
         */
        this.DateUpdated = this.constructor.DateUpdated.default ?? null;
        
        /**
         * @type {Number}
         */
        this.ID = this.constructor.ID.default ?? null;
        
        /**
         * @type {String}
         */
        this.ImageURL = this.constructor.ImageURL.default ?? null;
        
        /**
         * @type {String}
         */
        this.Name = this.constructor.Name.default ?? null;
        
        /**
         * @type {Number}
         */
        this.Price = this.constructor.Price.default ?? null;
        
        /**
         * @type {String}
         */
        this.ScanCode = this.constructor.ScanCode.default ?? null;
        
    }
    
    /**
     * StashKu property definition for Cost.
     * @type {Modeling.PropertyDefinition}
     */
    static get Cost() {
        return {
            target: 'Cost',
            type: 'Number'
        };
    }
    
    /**
     * StashKu property definition for DateCreated.
     * @type {Modeling.PropertyDefinition}
     */
    static get DateCreated() {
        return {
            target: 'Date_Created',
            type: 'String'
        };
    }
    
    /**
     * StashKu property definition for DateDeleted.
     * @type {Modeling.PropertyDefinition}
     */
    static get DateDeleted() {
        return {
            target: 'Date_Deleted',
            type: 'String'
        };
    }
    
    /**
     * StashKu property definition for DateUpdated.
     * @type {Modeling.PropertyDefinition}
     */
    static get DateUpdated() {
        return {
            target: 'Date_Updated',
            type: 'String'
        };
    }
    
    /**
     * StashKu property definition for ID.
     * @type {Modeling.PropertyDefinition}
     */
    static get ID() {
        return {
            target: 'ID',
            pk: true,
            type: 'Number'
        };
    }
    
    /**
     * StashKu property definition for ImageURL.
     * @type {Modeling.PropertyDefinition}
     */
    static get ImageURL() {
        return {
            target: 'Image_URL',
            type: 'String'
        };
    }
    
    /**
     * StashKu property definition for Name.
     * @type {Modeling.PropertyDefinition}
     */
    static get Name() {
        return {
            target: 'Name',
            type: 'String'
        };
    }
    
    /**
     * StashKu property definition for Price.
     * @type {Modeling.PropertyDefinition}
     */
    static get Price() {
        return {
            target: 'Price',
            type: 'Number'
        };
    }
    
    /**
     * StashKu property definition for ScanCode.
     * @type {Modeling.PropertyDefinition}
     */
    static get ScanCode() {
        return {
            target: 'Scan_Code',
            type: 'String'
        };
    }
    
    /**
     * The StashKu resource configuration for this model.
     * @type {Modeling.Configuration}
     */
    static get $stashku() {
        return {
            resource: 'products',
            name: 'Product',
            slug: 'product',
            plural: {
                name: 'Products',
                slug: 'products'
            }
        };
    }
    
}

export default BaseProductModel;
